 const dummyResponse = {
  "statusCode": 200,
  "message": "Success",
  "data": [{
      "id": 1,
      "companyId": 1,
      "postedBy": 4,
      "title": "Node JS",
      "department": 1,
      "description": "internship for Node JS position",
      "responsibilities": "Backend development",
      "requirements": "coding basic concepts",
      "internType": "FULL_TIME",
      "locationType": "ONSITE",
      "locationName": "UK",
      "salaryType": "PAID",
      "salaryFrequency": "MONTHLY",
      "salaryCurrency": "$",
      "salaryAmount": 2000,
      "totalPositions": 10,
      "closingDate": "2023-04-30",
      "duration": "6 months",
      "status": "PUBLISHED",
      "isDeleted": false,
      "createdAt": "2023-03-21T14:02:11.136Z",
      "updatedAt": "2023-03-21T14:02:11.136Z",
      "interns": [{
          "id": 1,
          "companyId": 1,
          "internshipId": 1,
          "userId": 3,
          "rating": null,
          "stage": "",
          "offerLetter": null,
          "userType": "Intern",
          "joiningDate": "2023-03-21T14:02:11.136Z",
          "internStatus": "employed",
          "internshipEndDate": null,
          "terminationReason": null,
          "assignedManager": 4,
          "createdAt": "2023-03-21T14:12:13.800Z",
          "updatedAt": "2023-03-21T14:12:13.800Z"
      }, {
          "id": 2,
          "companyId": 1,
          "internshipId": 1,
          "userId": 4,
          "rating": null,
          "stage": "applied",
          "offerLetter": null,
          "userType": "candidate",
          "joiningDate": null,
          "internStatus": null,
          "internshipEndDate": null,
          "terminationReason": null,
          "assignedManager": null,
          "createdAt": "2023-04-05T04:39:35.253Z",
          "updatedAt": "2023-04-05T04:39:35.253Z"
      }]
  }, {
      "id": 2,
      "companyId": 1,
      "postedBy": 4,
      "title": "React JS",
      "department": 1,
      "description": "Description",
      "responsibilities": "Responsibilities",
      "requirements": "Requirements",
      "internType": "PART_TIME",
      "locationType": "ONSITE",
      "locationName": "UK",
      "salaryType": "PAID",
      "salaryFrequency": "monthly",
      "salaryCurrency": "$",
      "salaryAmount": 200,
      "totalPositions": 10,
      "closingDate": "2023-05-22",
      "duration": "6 months",
      "status": "PUBLISHED",
      "isDeleted": false,
      "createdAt": "2023-04-07T05:06:56.094Z",
      "updatedAt": "2023-04-07T05:09:14.180Z",
      "interns": [{
          "id": 3,
          "companyId": 1,
          "internshipId": 2,
          "userId": 7,
          "rating": null,
          "stage": "applied",
          "offerLetter": null,
          "userType": "candidate",
          "joiningDate": null,
          "internStatus": null,
          "internshipEndDate": null,
          "terminationReason": null,
          "assignedManager": null,
          "createdAt": "2023-04-07T05:37:40.188Z",
          "updatedAt": "2023-04-07T05:37:40.188Z"
      }]
  }, {
      "id": 3,
      "companyId": 1,
      "postedBy": 6,
      "title": "Node JS",
      "department": 2,
      "description": "Description",
      "responsibilities": "Responsibilities",
      "requirements": "Requirements",
      "internType": "PART_TIME",
      "locationType": "ONSITE",
      "locationName": "UK",
      "salaryType": "PAID",
      "salaryFrequency": "monthly",
      "salaryCurrency": "$",
      "salaryAmount": 200,
      "totalPositions": 10,
      "closingDate": "2023-05-12",
      "duration": "6 months",
      "status": "PUBLISHED",
      "isDeleted": false,
      "createdAt": "2023-04-11T06:02:42.025Z",
      "updatedAt": "2023-04-11T06:02:42.025Z",
      "interns": []
  }],
  "count": 4,
  "pagination": {
      "page": 1,
      "limit": 10,
      "totalPages": 1,
      "resultCount": 3,
      "totalResult": 4
  },
  "error": null
}

export default dummyResponse;