version: "3.8"

services:
  app:
    container_name: studenthelpsquad
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - "3000:3000"
