import Logo from "../../../../../assets/images/serachJobs/logo.png";


export const AllJobsData = [
    {
        id: "1",
        coverPhoto: Logo,
        heading: "Power Source",
        location: "Oxford, UK",
        time: "Posted 45 mins ago",
        post: "Frontend Developer",
        description: "In this role, you will Write high quality, maintainable, reusable code following solid principles, Independently clarify technical requirements, develop coding estimates and apply a broad...",
        tags: ['utility bills', 'laundry', 'meals'],
    },
    {
        id: "2",
        coverPhoto: Logo,
        heading: "Power Source",
        location: "Liverpool, UK",
        time: "Posted 45 mins ago",
        post: "Data Analyst",
        description: "In this role, you will Write high quality, maintainable, reusable code following solid principles, Independently clarify technical requirements, develop coding estimates and apply a broad...",
        tags: ['utility bills', 'laundry', 'meals'],
    },
    {
        id: "3",
        coverPhoto: Logo,
        heading: "Power Source",
        location: "London, UK",
        time: "Posted 45 mins",
        post: "Business Analyst",
        description: "In this role, you will Write high quality, maintainable, reusable code following solid principles, Independently clarify technical requirements, develop coding estimates and apply a broad...",
        tags: ['utility bills', 'laundry', 'meals'],
    },
    {
        id: "4",
        coverPhoto: Logo,
        heading: "Power Source",
        location: "Manchester, UK",
        time: "Posted 45 mins",
        post: "Business Analyst",
        description: "In this role, you will Write high quality, maintainable, reusable code following solid principles, Independently clarify technical requirements, develop coding estimates and apply a broad...",
        tags: ['utility bills', 'laundry', 'meals'],
    },
    {
        id: "5",
        coverPhoto: Logo,
        heading: "Power Source",
        location: "London, UK",
        time: "Posted 45 mins ",
        post: "Ui Ux Designer",
        description: "In this role, you will Write high quality, maintainable, reusable code following solid principles, Independently clarify technical requirements, develop coding estimates and apply a broad...",
        tags: ['utility bills', 'laundry', 'meals'],
    },
    {
        id: "6",
        coverPhoto: Logo,
        heading: "Power Source",
        location: "York, UK",
        time: "Posted 45 mins ",
        post: "Data Analyst",
        description: "In this role, you will Write high quality, maintainable, reusable code following solid principles, Independently clarify technical requirements, develop coding estimates and apply a broad...",
        tags: ['utility bills', 'laundry', 'meals'],
    },

]