const roleBasedRoutes: any = {
  "/": ["Admin", "Manager", "Employee"],
  "/dashboard": ["Admin", "Manager", "Employee"],
  "/screencasts": ["Admin", "Manager", "Employee"],
  "/users-management": ["Admin"],
  "/users-management/edit-users": ["Admin", "Manager", "Employee"],
  "/integrations": ["Admin"],
  "/help": ["Admin", "Manager", "Employee"],
  "/latest-updates": ["Admin", "Manager", "Employee"],
  "/my-account": ["Admin", "Manager", "Employee"],
  "/security": ["Admin", "Manager", "Employee"],
  "/support-ticket": ["Admin", "Manager", "Employee"],

  "/reports/activity-log": ["Admin"],
  "/reports/project-task": ["Admin", "Manager", "Employee"],
  "/reports/project-task/:id": ["Admin", "Manager", "Employee"],
  "/reports/web-app-usage": ["Admin", "Employee"],
  "/reports/attendance": ["Admin", "Employee"],
  "/reports/top-users": ["Admin"],
  "/reports/timeline": ["Admin", "Employee"],
  "/reports/customized": ["Admin"],
  "/reports/hour-tracked": ["Admin", "Employee"],
  "/reports/workload-balance": ["Admin"],
  "/reports/comparison": ["Admin"],
  "/reports/timesheet": ["Admin", "Employee"],

  "/settings": ["Admin", "Manager"],
  "/settings/company-settings": ["Admin"],
  "/settings/work-schedule": ["Admin", "Manager"],
  "/settings/project-task": ["Admin", "Manager"],
  "/settings/manage-teams": ["Admin", "Manager"],
  "/settings/web-apps": ["Admin", "Manager"],
  "/settings/distraction-alerts": ["Admin", "Manager"],
  "/settings/scheduled-reports": ["Admin", "Manager", "Employee"],
  "/settings/achivements": ["Admin"],
  "/settings/blocking": ["Admin"],
  "/settings/email": ["Admin"],
};

export default roleBasedRoutes;
