import { LeaveProfileImg } from "../../../../assets/images";

export const calendarEventData = [
    {
        id: "1",
        title: "Sick",
        eventType: "sick",
        start: "2023-03-03T05:21:00",
        end: "2023-03-04T09:22:00",
        leaveTypeDay: "half day",
        dur: "01 day",
        hours: "04:00",
        img: LeaveProfileImg,
        name: "Maria Sanoid",
        designation: "UI UX Designer",
        email: "maria@Student Help Squad.com",
        aprover: "Amelia Clark",
        ApprovedBy: "Amelia Clark",
        status: "Pending",
        description: "As you know I don't have a car, and as it was announced there will be a strike the entire day within the public Transportation."
    },
    {
        id: "2",
        title: "Casual",
        eventType: "casual",
        start: "2023-03-04T01:21:00",
        end: "2023-03-05T05:22:00",
        leaveTypeDay: "full day",
        dur: "01 day",
        hours: "",
        img: LeaveProfileImg,
        name: "Maria Sanoid",
        designation: "UI UX Designer",
        email: "maria@Student Help Squad.com",
        aprover: "Amelia Clark",
        ApprovedBy: "Amelia Clark",
        status: "Pending",
        description: "As you know I don't have a car, and as it was announced there will be a strike the entire day within the public Transportation."
    },
    {
        id: "3",
        title: "Work from home",
        eventType: "work from home",
        start: "2023-03-06T06:21:00",
        end: "2023-03-08T07:22:00",
        leaveTypeDay: "half day",
        dur: "01 day",
        hours: "04:00",
        img: LeaveProfileImg,
        name: "Maria Sanoid",
        designation: "UI UX Designer",
        email: "maria@Student Help Squad.com",
        aprover: "Amelia Clark",
        ApprovedBy: "Amelia Clark",
        status: "Pending",
        description: "As you know I don't have a car, and as it was announced there will be a strike the entire day within the public Transportation."
    },
    {
        id: "4",
        title: "Medical",
        eventType: "medical",
        start: "2023-03-09T09:21:00",
        end: "2023-03-11T11:22:00",
        leaveTypeDay: "full day",
        dur: "01 day",
        hours: "",
        img: LeaveProfileImg,
        name: "Maria Sanoid",
        designation: "UI UX Designer",
        email: "maria@Student Help Squad.com",
        aprover: "Amelia Clark",
        ApprovedBy: "Amelia Clark",
        status: "Pending",
        description: "As you know I don't have a car, and as it was announced there will be a strike the entire day within the public Transportation.",
    }
]