import { LeaveProfileImg } from "../../assets/images";

interface DataType {
    key: string,
    title: string,
    eventType: string,
    requestDate: string,
    start: string,
    end: string,
    leaveTypeDay: string,
    dur: string,
    hours: string,
    img: any,
    name: string,
    designation: string,
    email: string,
    aprover: string,
    ApprovedBy: string,
    status: string,
    fulldescription: string
    leaveType: string,
    description: string,
    Actions: string,
  }
  export const data: any = [
    {
      key: '01',
      title: "Sick",
      eventType: "sick",
      requestDate: '2023-03-03',
      start: "2023-03-03T05:21:00",
      end: "2023-03-04T09:22:00",
      leaveTypeDay: "half day",
      dur: "01 day",
      hours: "04:00",
      img: LeaveProfileImg,
      name: "Maria Sanoid",
      designation: "UI UX Designer",
      email: "maria@Student Help Squad.com",
      aprover: "Amelia Clark",
      ApprovedBy: "Amelia Clark",
      status: "Pending",
      fulldescription: "As you know I don't have a car, and as it was announced there will be a strike the entire day within the public Transportation.",
      leaveType: 'sick',
      description: "High fever",
      Actions: "",
    },
    {
      key: "2",
      title: "Casual",
      eventType: "casual",
      requestDate: '2023-03-03',
      start: "2023-03-04T01:21:00",
      end: "2023-03-05T05:22:00",
      leaveTypeDay: "full day",
      dur: "01 day",
      hours: "",
      img: LeaveProfileImg,
      name: "Maria Sanoid",
      designation: "UI UX Designer",
      email: "maria@Student Help Squad.com",
      aprover: "Amelia Clark",
      ApprovedBy: "Amelia Clark",
      status: "Declined",
      fulldescription: "As you know I don't have a car, and as it was announced there will be a strike the entire day within the public Transportation.",
      leaveType: 'casual',
      description: "Casual",
      Actions: "",
    },
    {
      key: "3",
      title: "Work from home",
      eventType: "work from home",
      requestDate: '2023-03-03',
      start: "2023-03-06T06:21:00",
      end: "2023-03-08T07:22:00",
      leaveTypeDay: "half day",
      dur: "01 day",
      hours: "04:00",
      img: LeaveProfileImg,
      name: "Maria Sanoid",
      designation: "UI UX Designer",
      email: "maria@Student Help Squad.com",
      aprover: "Amelia Clark",
      ApprovedBy: "Amelia Clark",
      status: "Approved",
      fulldescription: "As you know I don't have a car, and as it was announced there will be a strike the entire day within the public Transportation.",
      leaveType: 'work from home',
      description: "work from home",
      Actions: "",
    },
    {
      key: "4",
      title: "Medical",
      eventType: "medical",
      requestDate: '2023-03-03',
      start: "2023-03-09T09:21:00",
      end: "2023-03-11T11:22:00",
      leaveTypeDay: "full day",
      dur: "01 day",
      hours: "",
      img: LeaveProfileImg,
      name: "Maria Sanoid",
      designation: "UI UX Designer",
      email: "maria@Student Help Squad.com",
      aprover: "Amelia Clark",
      ApprovedBy: "Amelia Clark",
      status: "Pending",
      fulldescription: "As you know I don't have a car, and as it was announced there will be a strike the entire day within the public Transportation.",
      leaveType: 'medical',
      description: "medical leave",
      Actions: "",
    }
  ];