export const CardData = [
    {
        id: '1',
        coverPhoto: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        discount: '30',
        autualPrice: '1800',
        withDiscountPrice: '1200',
        propertyAvailableFor: 'week',
        propertyType: 'apartment',
        totalBeds: '2',
        totalWashRoom: '2',
        tags: ['utility bills', 'laundry', 'meals'],
        location: 'location srtklgdfjgl',
    },
    {
        id: '2',
        coverPhoto: 'https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=1600',
        withDiscountPrice: '1200',
        propertyAvailableFor: 'month',
        propertyType: 'house',
        totalBeds: '2',
        totalWashRoom: '1',
        tags: ['utility bills', 'laundry', 'meals', 'others'],
        location: 'location srtklgdfjgl',
    },
    {
        id: '3',
        coverPhoto: 'https://images.pexels.com/photos/1370704/pexels-photo-1370704.jpeg',
        discount: '30',
        autualPrice: '1800',
        withDiscountPrice: '1200',
        propertyAvailableFor: 'night',
        propertyType: 'flat',
        totalBeds: '3',
        totalWashRoom: '2',
        tags: ['utility bills', 'laundry', 'meals'],
        location: 'location srtklgdfjgl',
    },
    {
        id: '4',
        coverPhoto: 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1600',
        discount: '30',
        autualPrice: '1800',
        withDiscountPrice: '1200',
        propertyAvailableFor: 'week',
        propertyType: 'apartment',
        totalBeds: '2',
        totalWashRoom: '2',
        tags: ['utility bills', 'laundry', 'meals', 'others'],
        location: 'location srtklgdfjgl',
    }
]